services:
  mysql8:
    container_name: mysql8
    image: mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: Inicio01
      MYSQL_DATABASE: msvc_usuarios
    volumes:
      - data-mysql:/var/lib/mysql
    restart: always
    networks:
      - spring

  postgres14:
    container_name: postgres14
    image: postgres:14-alpine
    ports:
      - "5532:5432"
    environment:
      POSTGRES_PASSWORD: Inicio01
      POSTGRES_DB: msvc_cursos
    volumes:
      - data-postgres:/var/lib/postgresql/data
    restart: always
    networks:
      - spring
  microservicio-usuarios:
    container_name: microservicio-usuarios
    build:
      context: ./
      dockerfile: ./microservicio-usuarios/Dockerfile
    ports:
      - "8001:8001"
    env_file:
      - ./microservicio-usuarios/.env
    networks:
      - spring
    depends_on:
      - mysql8
    restart: always

  microservicio-cursos:
    container_name: microservicio-cursos
    build:
      context: ./
      dockerfile: ./microservicio-cursos/Dockerfile
    ports:
      - "8002:8002"
    env_file:
      - ./microservicio-cursos/.env
    networks:
      - spring
    depends_on:
      - postgres14
      - microservicio-usuarios
    restart: always

volumes:
  data-mysql:
    name: data-mysql
  data-postgres:
    name: data-postgres

networks:
  spring:
    name: spring

